services:
  - type: web
    name: smart-voter-slip-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/ready
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: VOTERS_JSON_PATH
        value: ./database/voters.json
      - key: VOTERLIST_PDF_PATH
        value: ./pdf/voterlist.pdf
      - key: CORS_ORIGINS
        sync: false
